### PR TITLE
add geodns_link on rrset.meta

### PR DESCRIPTION
**Pull request by kokizzu**
image

### CODE REVIEW

**Comment by bazilek** [comment]
```
2023-08-14T18:56:55.338+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/g-core/gcore\"]" changed the config value, but that value is unused
gcore_dns_zone_record.f_cdn_vma_one: Modifying... [id={"Zone":"cdn.vma.one","Domain":"f.cdn.vma.one","Type":"A"}]
2023-08-14T18:56:55.478+0200 [ERROR] provider.terraform-provider-gcore: Response contains error diagnostic: @caller=/Users/bazilek/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_detail= diagnostic_summary="update zone rrset: 400: geodns_link must contain a valid domain name" tf_proto_version=5.3 tf_provider_addr=provider @module=sdk.proto diagnostic_severity=ERROR tf_req_id=8938f447-8bf8-2359-a310-9b15e77e2461 tf_resource_type=gcore_dns_zone_record tf_rpc=ApplyResourceChange timestamp=2023-08-14T18:56:55.478+0200
2023-08-14T18:56:55.489+0200 [ERROR] vertex "gcore_dns_zone_record.f_cdn_vma_one" error: update zone rrset: 400: geodns_link must contain a valid domain name
╷
│ Error: update zone rrset: 400: geodns_link must contain a valid domain name
│
│   with gcore_dns_zone_record.f_cdn_vma_one,
│   on dns.tf line 41, in resource "gcore_dns_zone_record" "f_cdn_vma_one":
│   41: resource "gcore_dns_zone_record" "f_cdn_vma_one" {
│
```

**Comment by bazilek** [comment]
```
2023-08-14T18:56:55.338+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/g-core/gcore\"]" changed the config value, but that value is unused
gcore_dns_zone_record.f_cdn_vma_one: Modifying... [id={"Zone":"cdn.vma.one","Domain":"f.cdn.vma.one","Type":"A"}]
2023-08-14T18:56:55.478+0200 [ERROR] provider.terraform-provider-gcore: Response contains error diagnostic: @caller=/Users/bazilek/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_detail= diagnostic_summary="update zone rrset: 400: geodns_link must contain a valid domain name" tf_proto_version=5.3 tf_provider_addr=provider @module=sdk.proto diagnostic_severity=ERROR tf_req_id=8938f447-8bf8-2359-a310-9b15e77e2461 tf_resource_type=gcore_dns_zone_record tf_rpc=ApplyResourceChange timestamp=2023-08-14T18:56:55.478+0200
2023-08-14T18:56:55.489+0200 [ERROR] vertex "gcore_dns_zone_record.f_cdn_vma_one" error: update zone rrset: 400: geodns_link must contain a valid domain name
╷
│ Error: update zone rrset: 400: geodns_link must contain a valid domain name
│
│   with gcore_dns_zone_record.f_cdn_vma_one,
│   on dns.tf line 41, in resource "gcore_dns_zone_record" "f_cdn_vma_one":
│   41: resource "gcore_dns_zone_record" "f_cdn_vma_one" {
│
```

**Review by bazilek — CHANGES_REQUESTED** [review]
fails on applying configuration without geodns_link

**Comment by kokizzu** [comment]
@bazilek what kind of tf file you set '__')? i tried with old one without geodns_link it works fine
```
provider gcore {
  permanent_api_token = "6483$xxx7f4"
}
terraform {
  required_providers {
    gcore = {
      source  = "local.gcore.com/repo/gcore"
      version = ">=0.3.64"
    }
  }
  required_version = ">= 0.13.0"
}
resource "gcore_dns_zone_record" "kokizzu_neuroops_link" {
  zone   = "kokizzu.neuroops.link"
  domain = "key542381339.kokizzu.neuroops.link"
  type   = "A"
  ttl    = 120

  meta {
    healthchecks {
      frequency        = 300
      protocol         = "HTTP"
      timeout          = 1
      host             = "echo.am3-hw-prod-2.p.gc.onl"
      http_status_code = 200
      method           = "GET"
      port             = 443
      tls              = true
      url              = "/"
    }
  }
  filter {
    limit  = 0
    strict = false
    type   = "is_healthy"
  }
  filter {
    limit  = 0
    strict = true
    type   = "geodns"
  }
  filter {
    limit  = 1
    strict = false
    type   = "first_n"
  }
  resource_record {
    content = "185.12.243.42"
    meta {
      fallback = true
    }
  }
  resource_record {
    content = "185.12.243.43"
    meta {
      backup = true
      weight = 10
    }
  }
  resource_record {
    content = "185.12.243.44"
    meta {
      countries  = ["ao", "dz"]
      continents = ["af", "eu"]
      latlong    = [
        0.151413, 103.700072
      ]
      notes = "test1"
      ip    = [
        "10.0.1.0/24"
      ]
    }
  }
}
```

**Review by bazilek — APPROVED** [review]

**Pull request merged**
